name: tienda
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  cupertino_icons: ^1.0.8
  badges: ^3.1.2
  curved_navigation_bar: ^1.0.6
  clippy_flutter: ^2.0.0-nullsafety.1
  flutter_rating_bar: ^4.0.1
  uuid: ^4.0.0
  http: ^0.13.6
  shared_preferences: ^2.2.2
  firebase_core: ^2.32.0 # ESTA ES LA VERSIÓN CORRECTA
  firebase_auth: ^4.20.0 # ÚLTIMA COMPATIBLE CON firebase_core ^2.32.0
  sqflite: ^2.3.2
  path: ^1.8.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
      - images/
  uses-material-design: true