// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL1vmuHg2schVTp62kGwdSs2bjC9-Eays',
    appId: '1:149534519771:web:5d9c353abc38055690f7fe',
    messagingSenderId: '149534519771',
    projectId: 'romafini',
    authDomain: 'romafini.firebaseapp.com',
    storageBucket: 'romafini.firebasestorage.app',
    measurementId: 'G-R2Q7LPDH8S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlPjtTLwC3aDx3rfUKktuNt6xAirgG4Yk',
    appId: '1:149534519771:android:230ece5edbe1f4d690f7fe',
    messagingSenderId: '149534519771',
    projectId: 'romafini',
    storageBucket: 'romafini.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2vqdjZ6-yBt_xt2aLTgJpOu9e1-EiF4M',
    appId: '1:149534519771:ios:d8e3d2d6bbe551e890f7fe',
    messagingSenderId: '149534519771',
    projectId: 'romafini',
    storageBucket: 'romafini.firebasestorage.app',
    iosBundleId: 'com.example.tienda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2vqdjZ6-yBt_xt2aLTgJpOu9e1-EiF4M',
    appId: '1:149534519771:ios:d8e3d2d6bbe551e890f7fe',
    messagingSenderId: '149534519771',
    projectId: 'romafini',
    storageBucket: 'romafini.firebasestorage.app',
    iosBundleId: 'com.example.tienda',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDL1vmuHg2schVTp62kGwdSs2bjC9-Eays',
    appId: '1:149534519771:web:af09eaad2a3641b590f7fe',
    messagingSenderId: '149534519771',
    projectId: 'romafini',
    authDomain: 'romafini.firebaseapp.com',
    storageBucket: 'romafini.firebasestorage.app',
    measurementId: 'G-RNQLC65NS7',
  );
}
